import js from '@eslint/js';
import tseslint from 'typescript-eslint';

export default tseslint.config(
  // next-env.d.ts is generated by Next and rewritten on every build; linting it is noise.
  {
    ignores: [
      '**/dist/**',
      '**/.next/**',
      '**/.turbo/**',
      '**/coverage/**',
      'local/**',
      'data/**',
      '**/next-env.d.ts',
      '**/.venv/**',
      '**/__pycache__/**',
    ],
  },
  js.configs.recommended,
  {
    // Node globals. Without this, every console.log in a script or server file is reported as
    // an undefined variable, which buries real findings under noise.
    languageOptions: {
      globals: {
        console: 'readonly',
        process: 'readonly',
        Buffer: 'readonly',
        fetch: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        URL: 'readonly',
        TextEncoder: 'readonly',
        TextDecoder: 'readonly',
        WebSocket: 'readonly',
        crypto: 'readonly',
        document: 'readonly',
        window: 'readonly',
        React: 'readonly',
      },
    },
  },
  ...tseslint.configs.recommended,
  {
    rules: {
      // No `any`; use `unknown` and narrow.
      '@typescript-eslint/no-explicit-any': 'error',
      '@typescript-eslint/consistent-type-imports': 'error',
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
      'no-empty': ['error', { allowEmptyCatch: true }],
    },
  },
  {
    // Only the LLM adapters may import `openai`.
    files: ['**/*.ts', '**/*.tsx'],
    ignores: ['packages/llm/src/adapters/**'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          paths: [
            {
              name: 'openai',
              message:
                'Import the LlmProvider interface from @han/llm instead. Only packages/llm/src/adapters/ may import the openai SDK.',
            },
          ],
        },
      ],
    },
  },
  {
    /**
     * Temporal workflow code is deterministic and sandboxed (§9.1).
     *
     * CORRECTED after building the worker. CONTRIBUTING.md says to replace `Date.now()` with
     * `workflow.now()` and `Math.random()` with `workflow.uuid4()`. The TypeScript SDK has
     * no `workflow.now()` at all, and its sandbox REPLACES the global `Date` and
     * `Math.random` — inside a workflow they are already deterministic and replay to the same
     * values. Banning them here rejected correct code and would have pushed the next person
     * toward an API that does not exist.
     *
     * What genuinely breaks determinism in this SDK is I/O and host randomness the sandbox
     * cannot intercept, so those are what the rules cover.
     */
    files: ['apps/worker/src/workflows/**/*.ts'],
    ignores: ['apps/worker/src/workflows/**/*.test.ts'],
    rules: {
      'no-restricted-globals': [
        'error',
        { name: 'fetch', message: 'Workflow code cannot do I/O — move it to an activity.' },
      ],
      'no-restricted-properties': [
        'error',
        {
          object: 'crypto',
          property: 'randomUUID',
          message: 'Not available in the workflow sandbox — use workflow.uuid4().',
        },
      ],
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            {
              group: ['node:fs', 'node:net', 'node:http*', 'pg', 'ioredis', 'openai', '@han/db*'],
              message:
                'Workflow code cannot reach the network, the database or the filesystem, even transitively — move it to an activity.',
            },
          ],
        },
      ],
    },
  },
);
