import js from '@eslint/js';
import tseslint from 'typescript-eslint';

export default tseslint.config(
  // next-env.d.ts is generated by Next and rewritten on every build; linting it is noise.
  { ignores: ['**/dist/**', '**/.next/**', '**/.turbo/**', '**/coverage/**', 'data/**', '**/next-env.d.ts', '**/.venv/**', '**/__pycache__/**'] },
  js.configs.recommended,
  {
    // Node globals. Without this, every console.log in a script or server file is reported as
    // an undefined variable, which buries real findings under noise.
    languageOptions: {
      globals: {
        console: 'readonly',
        process: 'readonly',
        Buffer: 'readonly',
        fetch: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        URL: 'readonly',
        TextEncoder: 'readonly',
        TextDecoder: 'readonly',
        WebSocket: 'readonly',
        crypto: 'readonly',
        document: 'readonly',
        window: 'readonly',
        React: 'readonly',
      },
    },
  },
  ...tseslint.configs.recommended,
  {
    rules: {
      // the spec §15 — no `any`; use `unknown` and narrow.
      '@typescript-eslint/no-explicit-any': 'error',
      '@typescript-eslint/consistent-type-imports': 'error',
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
    },
  },
  {
    // the spec §4.1 rule 4 — only the LLM adapters may import `openai`.
    files: ['**/*.ts', '**/*.tsx'],
    ignores: ['packages/llm/src/adapters/**'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          paths: [
            {
              name: 'openai',
              message:
                'Import the LlmProvider interface from @han/llm instead. Only packages/llm/src/adapters/ may import the openai SDK (the spec §4.1).',
            },
          ],
        },
      ],
    },
  },
  {
    // the spec §9.1 — Temporal workflow code is deterministic and sandboxed.
    files: ['apps/worker/src/workflows/**/*.ts'],
    rules: {
      'no-restricted-globals': [
        'error',
        { name: 'fetch', message: 'Workflow code cannot do I/O — move it to an activity.' },
      ],
      'no-restricted-properties': [
        'error',
        { object: 'Date', property: 'now', message: 'Use workflow.now() — workflow code must be deterministic.' },
        { object: 'Math', property: 'random', message: 'Use workflow.uuid4() — workflow code must be deterministic.' },
        { object: 'crypto', property: 'randomUUID', message: 'Use workflow.uuid4() — workflow code must be deterministic.' },
      ],
    },
  },
);
