import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { ALL_AGGREGATE_FLAGS, flag } from '@han/shared/flags';
import { ALL_STEP_STATUSES, KNOWN_SOURCE_IDS, StepStatus } from '@han/shared/status';

const ALL_STATUSES = ALL_STEP_STATUSES;
const ALL_SOURCES = KNOWN_SOURCE_IDS;

const STATUS_MEANING: Record<string, string> = {
  [StepStatus.HAS_RESULT]: 'The source ran and found something.',
  [StepStatus.NO_RESULT]: 'The source ran and found nothing. It looked.',
  [StepStatus.LOW_CONFIDENCE]: 'The source found something it does not trust enough to assert.',
  [StepStatus.ERROR]: 'The source failed. It did NOT look.',
  [StepStatus.TIMEOUT]: 'The source ran out of time. It did NOT finish looking.',
  [StepStatus.UNAVAILABLE]: 'The source is not configured or is down. It did NOT look.',
  [StepStatus.SKIPPED]: 'The source was deliberately not run. It did NOT look.',
  [StepStatus.NOT_EXECUTED]: 'The run never reached this source at all.',
};

function main(): void {
  const out: string[] = [];

  out.push('# Flags');
  out.push('');
  out.push('**Generated by `pnpm flags:docs`. Do not edit by hand.**');
  out.push('');
  out.push('Source: `packages/shared/src/flags.ts` and `packages/shared/src/status.ts`.');
  out.push('');
  out.push('There are exactly two kinds of flag (§5.1). Nothing outside the registry may build');
  out.push('one from a string literal.');
  out.push('');

  out.push('## Statuses');
  out.push('');
  out.push('Every one of these means something different. Collapsing any of them into');
  out.push('`no_result` turns "we could not look" into "there is nothing there".');
  out.push('');
  out.push('| status | meaning |');
  out.push('| --- | --- |');
  for (const s of ALL_STATUSES) {
    out.push(`| \`${s}\` | ${STATUS_MEANING[s] ?? ''} |`);
  }
  out.push('');

  out.push('## Derived flags');
  out.push('');
  out.push('Mechanically `${source}_${status}`, one row per source, one column per status.');
  out.push('All of them are legal; which ones a given source can actually emit depends on what');
  out.push('that source does.');
  out.push('');
  out.push(`| source | ${ALL_STATUSES.join(' | ')} |`);
  out.push(`| --- | ${ALL_STATUSES.map(() => '---').join(' | ')} |`);
  for (const source of ALL_SOURCES) {
    const cells = ALL_STATUSES.map((s) => `\`${flag(source, s)}\``);
    out.push(`| **${source}** | ${cells.join(' | ')} |`);
  }
  out.push('');
  out.push(
    `${ALL_SOURCES.length} sources x ${ALL_STATUSES.length} statuses = ${ALL_SOURCES.length * ALL_STATUSES.length} derived flags.`,
  );
  out.push('');

  out.push('## Aggregate flags');
  out.push('');
  out.push('Conclusions drawn ACROSS sources — a judgement, not a status, which is why no');
  out.push('source/status pair produces them and why they are hand-registered.');
  out.push('');
  out.push('| flag |');
  out.push('| --- |');
  for (const f of ALL_AGGREGATE_FLAGS) out.push(`| \`${f}\` |`);
  out.push('');

  const path = fileURLToPath(new URL('../docs/flags.md', import.meta.url));
  writeFileSync(path, `${out.join('\n')}\n`, 'utf8');
  console.log(
    `docs/flags.md — ${ALL_SOURCES.length * ALL_STATUSES.length} derived, ${ALL_AGGREGATE_FLAGS.length} aggregate`,
  );
}

main();
